account/urls.py
from django.urls import path
from account import views
from .views import CustomLoginView
urlpatterns = [
    path("create_account/",views.create_account,name='register'),
    path("login/",CustomLoginView.as_view(),name='login'),
    path("my_account/",views.my_account,name='my_account'),
]

home/urls.py
from django.urls import path
from home import views


urlpatterns= [ 
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("add/",views.add_question,name='add_question')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

app_name="home"
urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('home.urls')),  
    path('account/', include('account.urls')), 
] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



account/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager,  Group, Permission
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

class account(AbstractBaseUser):
  groups = models.ManyToManyField(Group, related_name="custom_user_set")
  user_permissions = models.ManyToManyField(Permission, related_name="custom_user_permissions_set")
    
  username = models.CharField(max_length=50,unique=True)
  email = models.EmailField(unique=True,null=True)
  is_active = models.BooleanField(default=True)
  is_staff = models.BooleanField(default=False)
  bio = models.CharField(max_length=200,blank=True)
  profile_picture = CloudinaryField('image', blank=True, null=True)

  objects = CustomUserManager()
  
  USERNAME_FIELD = 'username'
  REQUIRED_FIELDS = ['email']

  def __str__(self):
      return self.username

home/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib import admin
from cloudinary.models import CloudinaryField
from django.conf import settings


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    image = CloudinaryField('image', blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,default=1)
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return f"{self.choice_text} {str(self.votes)}"

account/forms.py
from cloudinary.forms import CloudinaryFileField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import account 

class AccountCreationForm(UserCreationForm):
    class Meta:
        model = account
        fields = ('username','email', 'bio','profile_picture')



        

home/forms.py
from django import forms
from home.models import Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields =['question_text','pub_date','image']

account/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from .forms import AccountCreationForm
from django.contrib.auth.decorators import login_required

def create_account(request):
    if request.method == 'POST':
        form = AccountCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)  # Automatically log the user in after registration
            return redirect('')  # Redirect to the homepage or any other page
    else:
        form = AccountCreationForm()
    return render(request, 'account/creat_account.html', {'form': form})

class CustomLoginView(LoginView):
    template_name = 'account/login.html'
@login_required
def my_account(request):
    templet_name='account/my_account.html'

home/views.py
from django.shortcuts import get_object_or_404, render,redirect
from .models import Question,Choice
from django.http import  HttpResponseRedirect
from django.urls import reverse
from django.db.models import F
from django.views import generic
from django.utils import timezone
from .forms import QuestionForm
from account.models import account as User
from django.contrib.auth.decorators import login_required
import IP2Location
from django.http import JsonResponse

db = IP2Location.IP2Location("db/IP2LOCATION-LITE-DB1.BIN")

def get_country(request):
    user_ip = request.META.get('REMOTE_ADDR')  # Get the user's IP address
    record = db.get_all(user_ip)
    country = record.country_short

    return country

class IndexView(generic.ListView):
    template_name = "home/index.html"
    context_object_name = "question_list"
    users=User.objects.filter(is_staff=False)
    country=get_country
    extra_context = {'users': users,'country':country}
    
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by
        ("-pub_date")


class DetailView(generic.DetailView):
    model = Question
    template_name = "home/detail.html"
    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = "home/results.html"

    
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "home/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("home:results", args=(question.id,)))
@login_required
def add_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST,request.FILES)
        if form.is_valid():
            form.instance.user = request.user 
            form.save()
            return redirect("/home")
    else:
        form=QuestionForm()
    return render(request,'addquestion.html',{'form':form})


home/templates/addquestion.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Question</title>
</head>
<body>
    <h2>Add a New Question</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</body>
</html>

home/templates/home/detail.html
    {%load static%}
    <link rel="stylesheet" href="{% static 'home/style2.css' %}">
    <a href="{% url 'home:index' %}">back to home</a>
    <form action="{% url 'home:vote' question.id %}" method="post">
    {% csrf_token %}
    <p>question {{question.id}} </p>
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">


    </form>

home/templates/home/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'home/style.css' %}">

<div class='top'>

    <div class='rectungel'>logo</div>
    <div class='rectungel'>  about  </div>
    <div id='empty'>      </div>
    <div class='search'>  search bar  </div>
    <div id='empty'>      </div>
    <div class='rectungel'>  page2  </div>
    <div class='contry'>  {{country}}  </div>
    
</div >

<div class='posting'>

<p class='greating'>welcome to the public chat {{user.username}}</p>
<a  href='/add' class='add_question_button'> add question</a>

</div>
<div class='profile_home'>
    <img class="image" src="{{ user.profile_pic.url }}" alt="Profile Image">
</div>

<h1 >the available questions</h1>

<div class="container">
    <div class="users">

    {% for user in users %}
        <div class='username'>
        <div class='pfp'>
        </div>
        {{ user.username }}
        </div>
    {% endfor %}

    </div>

    <div class="question">

    {% if question_list %}
        {% for question in question_list %}

            {% if question.image %}
            <q>
                <div>prfile pic   {{question.user}}</div>
                <img class="image" src="{{ question.image.url }}" alt="Question 
                Image">

            {% else %}

                <q> 
                    <div>prfile pic   {{user.username}}</div>
                    <img class="image"  src="{% static 'home/images/background.png' %}" alt="No Image Available">

            {% endif %}
                <a href="/home/{{ question.id }}/" class='question_text'> {{ question.question_text }}
                </a></q></q>
       {% endfor %}
    {% else %}
        <p>No questions are available.</p>
    {% endif %}
        
    </div>
    <div class="ads"> ads here</div>
</div>


home/templates/home/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'home:detail' question.id %}">Vote again?</a>